rbac:
  create: false
serviceAccount:
  create: false
service:
  type: ClusterIP # default
  annotations:
    dev.okteto.com/auto-ingress: "private"
persistence:
  type: pvc # default
  enabled: true
  size: 2Gi
grafana.ini:
  auth.anonymous:
    enabled: "true"
    org_name: Main Org.
    org_role: Admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 60s
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: "Okteto"
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    activity:
      name: "activity"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/Activity.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    builds:
      name: "builds"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/Builds.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    clusterNodes:
      name: "clusterNodes"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/cluster-nodes.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    deploy:
      name: "deploy"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/Deploy.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    home:
      name: "home"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/home.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    namespace:
      name: "namespace"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/Namespace.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    nodes:
      name: "nodes"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/nodes.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    pods:
      name: "pods"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/pods.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    test:
      name: "test"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/refs/tags/0.0.0-20250306/dashboards/test.json"
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
