rbac:
  create: false
serviceAccount:
  create: false
service:
  type: ClusterIP # default
  annotations:
    dev.okteto.com/auto-ingress: "private"
persistence:
  type: pvc # default
  enabled: true
  size: 2Gi
grafana.ini:
  auth.anonymous:
    enabled: "true"
    org_name: Main Org.
    org_role: Admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 60s
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'Okteto'
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    pods:
      name: "Pods"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/main/dashboards/pods.json"
      datasource:
      - name: DS_PROMETHEUS
        value: Prometheus
    nodes:
      name: "Nodes"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/main/dashboards/nodes.json"
      datasource:
      - name: DS_PROMETHEUS
        value: Prometheus
    namespacesPreviewsAndUsers:
      name: "Namespaces, Previews and Users"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/main/dashboards/namespaces-previews-and-users.json"
      datasource:
      - name: DS_PROMETHEUS
        value: Prometheus
    buildAndDeploy:
      name: "Build and Deploy"
      url: "https://raw.githubusercontent.com/okteto/insights-dashboards/main/dashboards/build-and-deploy.json"
      datasource:
      - name: DS_PROMETHEUS
        value: Prometheus
