{
 "title": "Activity",
 "description": "Copyright 2024 The Okteto Authors\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
 "tags": [
  "dashboard",
  "okteto"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(okteto_system_user_last_seen_time)",
     "legendFormat": "Total Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(okteto_system_user_last_seen_time[$__interval]) > 0)",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(count_over_time(okteto_system_pod_container_cpu_requests_cores{pod_type=\"development\"}[$__range])) by (namespace, controller_name)) or vector(0)",
     "legendFormat": "Development Containers"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(increase(okteto_system_user_last_seen_time[$__interval])>0)",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Development Containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(count(okteto_system_pod_container_cpu_requests_cores{pod_type=\"development\"}) by (pod_names)) or vector(0)",
     "legendFormat": "Development Containers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(okteto_system_namespace_created_time)",
     "legendFormat": "Total Namespaces"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"active\"})",
     "legendFormat": "Active Namespaces"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"sleeping\"})",
     "legendFormat": "Sleeping Namespaces"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(okteto_system_preview_created_time)",
     "legendFormat": "Total Previews"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_preview_status_condition{condition=\"active\"})",
     "legendFormat": "Active Previews"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_preview_status_condition{condition=\"sleeping\"})",
     "legendFormat": "Sleeping Previews"
    }
   ]
  },
  {
   "title": "Active Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"active\"})",
     "legendFormat": "Active namespaces"
    }
   ]
  },
  {
   "title": "Active Previews",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(okteto_system_preview_status_condition{}[$__interval])) or vector(0)\n",
     "legendFormat": "Previews"
    }
   ]
  }
 ]
}