{
 "title": "Build Service",
 "description": "Copyright 2025 The Okteto Authors\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
 "tags": [
  "okteto",
  "dashboard"
 ],
 "time": { "from": "now-30d", "to": "now-5m" },
 "templating": {
  "list": [
   {
    "name": "buildkitPod",
    "label": "Pod",
    "query": {
     "query": "label_values(okteto_build_cpu_total_millicores,kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  count by (kubernetes_pod_name) (\n    okteto_build_cpu_total_millicores\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active Builds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(okteto_build_active_builds)",
     "legendFormat": "Concurrent Builds"
    }
   ]
  },
  {
   "title": "\"$buildkitPod\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "buildkitPod"
  },
  {
   "title": "Active Builds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(okteto_build_active_builds{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "Concurrent Builds"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 *\nrate(okteto_build_cpu_usage_milliseconds_total{kubernetes_pod_name=\"$buildkitPod\"}[$__rate_interval])\n/\nokteto_build_cpu_total_millicores{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(okteto_build_memory_usage_bytes{kubernetes_pod_name=\"$buildkitPod\"} / okteto_build_memory_total_bytes{kubernetes_pod_name=\"$buildkitPod\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(okteto_build_cpu_pressure{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(okteto_build_cpu_throttled_milliseconds_total{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(okteto_build_disk_read_ops_total{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(okteto_build_disk_write_ops_total{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "IO Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum(okteto_build_io_pressure{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(okteto_build_inodes_total{kubernetes_pod_name=\"$buildkitPod\"} - okteto_build_inodes_usage{kubernetes_pod_name=\"$buildkitPod\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}