{
 "title": "Build & Deploy",
 "description": "Copyright 2024 The Okteto Authors\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
 "tags": [
  "okteto",
  "dashboard"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "devenv", "label": "Development Environment", "query": { "query": "label_values(devenv_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Build count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "builds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_result{result!=\"skipped\"})",
     "legendFormat": "Total Build count"
    }
   ]
  },
  {
   "title": "Total Build time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_duration_seconds_sum)",
     "legendFormat": "Total build time"
    }
   ]
  },
  {
   "title": "Smart Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_result{result=\"skipped\"}) / sum(okteto_usage_build_result{})",
     "legendFormat": "Percentage"
    },
    {
     "expr": "sum(okteto_usage_build_duration_seconds_sum{}) / sum(okteto_usage_build_duration_seconds_count{}) * sum(okteto_usage_build_result{result=\"skipped\"})",
     "legendFormat": "Time saved on average"
    }
   ]
  },
  {
   "title": "Total Deploy count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "builds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_deploy_result)",
     "legendFormat": "Total Deploy count"
    }
   ]
  },
  {
   "title": "Total Deploy time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_deploy_duration_seconds_sum)",
     "legendFormat": "Total deploy time"
    }
   ]
  },
  {
   "title": "Development environment \"${devenv}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Total Build count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "builds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_result{devenv_name=\"${devenv}\", result!=\"skipped\"})",
     "legendFormat": "Total Build count"
    }
   ]
  },
  {
   "title": "Total Build time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_duration_seconds_sum{devenv_name=\"${devenv}\"})",
     "legendFormat": "Total build time"
    }
   ]
  },
  {
   "title": "Smart Builds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_result{devenv_name=\"${devenv}\", result=\"skipped\"}) / sum(okteto_usage_build_result{devenv_name=\"${devenv}\"})",
     "legendFormat": "Percentage"
    },
    {
     "expr": "sum(okteto_usage_build_duration_seconds_sum{devenv_name=\"$devenv\"}) / sum(okteto_usage_build_duration_seconds_count{devenv_name=\"$devenv\"}) * sum(okteto_usage_build_result{devenv_name=\"$devenv\", result=\"skipped\"})",
     "legendFormat": "Time saved on average"
    }
   ]
  },
  {
   "title": "Total Deploy count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "builds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_deploy_result{devenv_name=\"${devenv}\"})",
     "legendFormat": "Total Deploy count"
    }
   ]
  },
  {
   "title": "Total Deploy time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_deploy_duration_seconds_sum{devenv_name=\"${devenv}\"})",
     "legendFormat": "Total deploy time"
    }
   ]
  },
  {
   "title": "Average Build time per image",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_build_duration_seconds_sum{devenv_name=\"$devenv\"}) by (image_name) / sum(okteto_usage_build_duration_seconds_count{devenv_name=\"$devenv\"}) by (image_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Deploy time per phase",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_usage_deploy_duration_seconds_sum{devenv_name=\"$devenv\"}) by (phase) / sum(okteto_usage_deploy_duration_seconds_count{devenv_name=\"$devenv\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}