{
 "title": "Namespaces & Previews",
 "description": "Copyright 2024 The Okteto Authors\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
 "tags": [
  "dashboard",
  "okteto"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Namespace count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(okteto_system_namespace_created_time)",
     "legendFormat": "Total namespaces"
    },
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"active\"})",
     "legendFormat": "Active namespaces"
    },
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"sleeping\"})",
     "legendFormat": "Sleeping namespaces"
    }
   ]
  },
  {
   "title": "Preview count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(okteto_system_preview_created_time)",
     "legendFormat": "Total previews"
    },
    {
     "expr": "sum(okteto_system_preview_status_condition{condition=\"active\"})",
     "legendFormat": "Active previews"
    },
    {
     "expr": "sum(okteto_system_preview_status_condition{condition=\"sleeping\"})",
     "legendFormat": "Sleeping previews"
    }
   ]
  },
  {
   "title": "Active Namespaces over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(okteto_system_namespace_status_condition{condition=\"active\"})",
     "legendFormat": "Active namespaces"
    }
   ]
  },
  {
   "title": "Previews over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(okteto_system_preview_status_condition{scope=\"global\"})",
     "legendFormat": "Global previews"
    },
    {
     "expr": "sum(okteto_system_preview_status_condition{scope=\"personal\"})",
     "legendFormat": "Personal previews"
    }
   ]
  }
 ]
}