{
 "title": "Pods",
 "description": "Copyright 2024 The Okteto Authors\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
 "tags": [
  "okteto",
  "dashboard"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(okteto_system_pod_container_cpu_requests_cores,namespace)"
    }
   },
   {
    "name": "devenv",
    "label": "Development Environment",
    "query": {
     "query": "label_values(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\"},devenv_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Pods" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\"}) by (namespace, pod_name))",
     "legendFormat": "Pod Count"
    }
   ]
  },
  {
   "title": "Requested CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(sum(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\"}) by (pod) + max(okteto_system_pod_init_container_cpu_requests_cores{namespace=\"$namespace\"}) by (pod)) by (pod))",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\"})",
     "legendFormat": "Used CPU"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(sum(okteto_system_pod_container_memory_requests_bytes{namespace=\"$namespace\"}) by (pod) + max(okteto_system_pod_init_container_memory_requests_bytes{namespace=\"$namespace\"}) by (pod)) by (pod))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(okteto_system_pod_container_memory_usage_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Pods over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(sum(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "Pods over time at namespace \"${namespace}\""
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(okteto_system_pod_container_memory_usage_bytes{namespace=\"$namespace\"})",
     "legendFormat": " Memory Usage"
    }
   ]
  },
  {
   "title": "Development Environment \"${devenv}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "devenv"
  },
  {
   "title": "Number of deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deployments" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"deployment\", pod_type=\"standard\"}) by (controller_name))",
     "legendFormat": "Number of deployments"
    }
   ]
  },
  {
   "title": "Number of statefulsets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "statefulsets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"statefulset\", pod_type=\"standard\"}) by (controller_name)) ",
     "legendFormat": "Number of statefulsets"
    }
   ]
  },
  {
   "title": "Number of pods in Development mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(okteto_system_pod_container_cpu_requests_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", pod_type=\"development\"}) by (pod_names))",
     "legendFormat": "Number of pods in Development mode"
    }
   ]
  },
  {
   "title": "Average CPU usage per pod by Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"deployment\", pod_type=\"standard\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average CPU usage per pod by Statefulset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"statefulset\", pod_type=\"standard\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average CPU usage per pod in Development mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_cpu_usage_cores{namespace=\"$namespace\", devenv_name=\"$devenv\", pod_type=\"development\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Memory usage per pod by Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_memory_usage_bytes{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"deployment\", pod_type=\"standard\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Memory usage per pod by Statefulset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_memory_usage_bytes{namespace=\"$namespace\", devenv_name=\"$devenv\", controller_type=\"statefulset\", pod_type=\"standard\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Memory usage per pod in Development mode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(okteto_system_pod_container_memory_usage_bytes{namespace=\"$namespace\", devenv_name=\"$devenv\", pod_type=\"development\"}) by (controller_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}